local UIS,PLRS,RS,TS,CG,W,RS_S,HS,TCS,CAS=game:GetService("UserInputService"),game:GetService("Players"),game:GetService("RunService"),game:GetService("TweenService"),game:GetService("CoreGui"),game:GetService("Workspace"),game:GetService("ReplicatedStorage"),game:GetService("HttpService"),game:GetService("TextChatService"),game:GetService("ContextActionService")
local lp=PLRS.LocalPlayer;local ScreenGui=Instance.new("ScreenGui",CG)ScreenGui.Name="IrishHub_Official"ScreenGui.ResetOnSpawn=false
local COLORS={MainBG=Color3.fromRGB(11,14,20),TabBG=Color3.fromRGB(15,20,28),Border=Color3.fromRGB(0,170,0),TextActive=Color3.fromRGB(0,170,0),TextInactive=Color3.fromRGB(140,140,140),RowBG=Color3.fromRGB(18,24,35)}
local function create(c,p)local o=Instance.new(c)for k,v in pairs(p)do if k~="Parent"then o[k]=v end end;o.Parent=p.Parent;return o end
local configFile,Config,ToggleStates,LockUIMove,Keybinds="Irish_Hub_Duels_config.json",{},{},false,{}
local Float,Taunt,SpeedVisual,Fov,TpDown,AutoMedusa,InfiniteJump={Enabled=false},{Enabled=false},{Enabled=false},{Enabled=false},{Enabled=false},{Enabled=false,lastUse=0},{Enabled=true,jumpForce=54,clampFallSpeed=130}
local function drag(obj)local d,di,ds,sp;obj.InputBegan:Connect(function(i)if not LockUIMove and(i.UserInputType==Enum.UserInputType.MouseButton1 or i.UserInputType==Enum.UserInputType.Touch)then d=true;ds=i.Position;sp=obj.Position;i.Changed:Connect(function()if i.InputState==Enum.UserInputState.End then d=false end end)end end)obj.InputChanged:Connect(function(i)if i.UserInputType==Enum.UserInputType.MouseMovement or i.UserInputType==Enum.UserInputType.Touch then di=i end end)UIS.InputChanged:Connect(function(i)if i==di and d then local dl=i.Position-ds;obj.Position=UDim2.new(sp.X.Scale,sp.X.Offset+dl.X,sp.Y.Scale,sp.Y.Offset+dl.Y)end end)end
local function createSpeedVisual()local c=lp.Character or lp.CharacterAdded:Wait()local r=c:WaitForChild("HumanoidRootPart")if SpeedVisual.speedBB then SpeedVisual.speedBB:Destroy() end;SpeedVisual.speedBB=Instance.new("BillboardGui",r)SpeedVisual.speedBB.Size,SpeedVisual.speedBB.StudsOffset,SpeedVisual.speedBB.AlwaysOnTop=UDim2.new(0,120,0,36),Vector3.new(0,4.5,0),true;local l=Instance.new("TextLabel",SpeedVisual.speedBB)l.Size,l.BackgroundTransparency,l.TextColor3,l.TextStrokeTransparency,l.TextScaled,l.Text=UDim2.new(1,0,1,0),1,Color3.new(1,1,1),0,true,"Speed: 0"end
RS.Heartbeat:Connect(function()if SpeedVisual.Enabled and lp.Character and lp.Character:FindFirstChild("HumanoidRootPart")then local r=lp.Character.HumanoidRootPart;if not SpeedVisual.speedBB or not SpeedVisual.speedBB.Parent then createSpeedVisual()end;local l=SpeedVisual.speedBB:FindFirstChildOfClass("TextLabel")if l then l.Text="Speed: "..math.floor(Vector3.new(r.AssemblyLinearVelocity.X,0,r.AssemblyLinearVelocity.Z).Magnitude)end end end)
UIS.JumpRequest:Connect(function()if InfiniteJump.Enabled and lp.Character and lp.Character:FindFirstChild("HumanoidRootPart")then lp.Character.HumanoidRootPart.AssemblyLinearVelocity=Vector3.new(lp.Character.HumanoidRootPart.AssemblyLinearVelocity.X,InfiniteJump.jumpForce,lp.Character.HumanoidRootPart.AssemblyLinearVelocity.Z)end end)
local ToggleIcon=create("TextButton",{Size=UDim2.new(0,45,0,45),Position=UDim2.new(0.05,0,0.2,0),BackgroundColor3=COLORS.MainBG,Text="☘️",TextColor3=COLORS.Border,Font="GothamBold",TextSize=20,Parent=ScreenGui})create("UICorner",{CornerRadius=UDim.new(0,8),Parent=ToggleIcon})create("UIStroke",{Color=COLORS.Border,Thickness=1.5,Parent=ToggleIcon})
local MainFrame=create("Frame",{Size=UDim2.new(0,380,0,480),Position=UDim2.new(0.5,-190,0.5,-240),BackgroundColor3=COLORS.MainBG,BackgroundTransparency=0.2,Visible=false,Parent=ScreenGui})create("UICorner",{CornerRadius=UDim.new(0,12),Parent=MainFrame})create("UIStroke",{Color=COLORS.Border,Thickness=2,Parent=MainFrame})
ToggleIcon.MouseButton1Click:Connect(function()MainFrame.Visible=not MainFrame.Visible end)drag(ToggleIcon)drag(MainFrame)
